"""
University Knowledge Base
==========================
Featured programs and top-20 rankings for hundreds of US universities.
Used by scrape_programs.py to apply correct featured program data.

Each entry: key = lowercase substring(s) of university name
            value = featured program info + top-20 list
"""

KNOWN_FEATURED = {

    # ── TEXAS UNIVERSITIES ─────────────────────────────────────────────────
    "north texas": {
        "featured_name": "Bachelor of Music in Jazz Studies",
        "reputation_note": "UNT Jazz Studies is ranked #1 in the nation — the first accredited jazz program in the US, with alumni including Pat Metheny and Don Henley.",
        "program_url": "https://music.unt.edu/areas-of-study/jazz-studies",
        "top20": ["Bachelor of Music in Jazz Studies","Master of Music in Jazz Studies",
                  "Master of Science in Data Science","Doctor of Musical Arts",
                  "Bachelor of Science in Merchandising","Doctor of Philosophy in Audiology",
                  "Master of Science in Information Science","Bachelor of Fine Arts in Studio Art",
                  "Master of Public Health","Bachelor of Arts in Radio, Television and Film",
                  "Bachelor of Science in Computer Science","Master of Business Administration"],
    },
    "university of texas at austin": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "UT Austin CS is ranked top-10 nationally and is part of one of the largest CS departments in the US, with exceptional research in AI and systems.",
        "program_url": "https://www.cs.utexas.edu/undergraduate",
        "top20": ["Bachelor of Science in Computer Science","Bachelor of Science in Petroleum Engineering",
                  "Master of Business Administration","Bachelor of Arts in Liberal Arts",
                  "Master of Science in Computer Science","Bachelor of Science in Electrical Engineering"],
    },
    "texas a&m": {
        "featured_name": "Bachelor of Science in Engineering",
        "reputation_note": "Texas A&M Engineering is one of the largest engineering schools in the US, consistently ranked top 10 nationally for undergraduate engineering education.",
        "program_url": "https://engineering.tamu.edu/undergraduate",
        "top20": ["Bachelor of Science in Engineering","Bachelor of Science in Computer Science",
                  "Bachelor of Science in Petroleum Engineering","Master of Business Administration",
                  "Bachelor of Science in Agriculture"],
    },
    "rice university": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "Rice CS is ranked top-20 globally and sits at the heart of Houston's booming tech sector, with an exceptional student-to-faculty ratio.",
        "program_url": "https://csweb.rice.edu/academics/undergraduate-programs",
        "top20": ["Bachelor of Science in Computer Science","Bachelor of Arts in Economics",
                  "Bachelor of Science in Bioengineering","Bachelor of Music"],
    },
    "baylor university": {
        "featured_name": "Doctor of Medicine",
        "reputation_note": "Baylor College of Medicine is consistently ranked top-5 for NIH research funding and is one of the nation's premier academic medical centers.",
        "program_url": "https://www.bcm.edu/education/medical-school",
        "top20": ["Doctor of Medicine","Master of Business Administration",
                  "Bachelor of Science in Computer Science","Juris Doctor"],
    },
    "texas tech": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "Texas Tech's Rawls College of Business MBA is AACSB-accredited and highly ranked for supply chain management and entrepreneurship in West Texas.",
        "program_url": "https://www.depts.ttu.edu/rawlsbusiness/graduate/mba",
        "top20": ["Master of Business Administration","Bachelor of Science in Computer Science",
                  "Bachelor of Science in Petroleum Engineering"],
    },
    "university of houston": {
        "featured_name": "Bachelor of Science in Petroleum Engineering",
        "reputation_note": "UH's Petroleum Engineering program is ranked top-5 nationally and produces more petroleum engineers entering the oil & gas industry than nearly any other school.",
        "program_url": "https://www.egr.uh.edu/petroleum",
        "top20": ["Bachelor of Science in Petroleum Engineering","Master of Business Administration",
                  "Bachelor of Science in Computer Science","Doctor of Pharmacy"],
    },
    "southern methodist": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "SMU's Cox School of Business MBA is ranked top-25 nationally with exceptional career placement in energy, finance, and consulting sectors.",
        "program_url": "https://www.cox.smu.edu/mba",
        "top20": ["Master of Business Administration","Juris Doctor",
                  "Bachelor of Science in Computer Science"],
    },
    "trinity university": {
        "featured_name": "Bachelor of Arts in Business Administration",
        "reputation_note": "Trinity is ranked #1 regional university in the West for business, known for exceptional undergraduate teaching and small class sizes.",
        "program_url": "https://new.trinity.edu/academics/departments/business",
        "top20": ["Bachelor of Arts in Business Administration","Bachelor of Science in Computer Science"],
    },
    "sam houston": {
        "featured_name": "Bachelor of Science in Criminal Justice",
        "reputation_note": "SHSU's Criminal Justice program is one of the largest and most respected in the nation, with a dedicated College of Criminal Justice.",
        "program_url": "https://www.shsu.edu/academics/criminal-justice",
        "top20": ["Bachelor of Science in Criminal Justice","Master of Business Administration"],
    },
    "texas state": {
        "featured_name": "Bachelor of Science in Health Administration",
        "reputation_note": "Texas State's Health Administration program is nationally accredited (AUPHA) and highly ranked for healthcare management training in Texas.",
        "program_url": "https://www.health.txstate.edu",
        "top20": ["Bachelor of Science in Health Administration","Master of Business Administration",
                  "Bachelor of Science in Computer Science"],
    },
    "ut dallas": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "UT Dallas CS is ranked top-50 nationally and is the heart of Silicon Prairie, with exceptional ties to Texas Instruments, AT&T, and major tech firms.",
        "program_url": "https://cs.utdallas.edu/education/undergraduate",
        "top20": ["Bachelor of Science in Computer Science","Master of Science in Computer Science",
                  "Master of Business Administration"],
    },
    "ut san antonio": {
        "featured_name": "Master of Science in Cybersecurity",
        "reputation_note": "UTSA is designated a National Center of Academic Excellence in Cybersecurity by NSA/DHS and is ranked #1 in Texas for cybersecurity programs.",
        "program_url": "https://cybersecurity.utsa.edu",
        "top20": ["Master of Science in Cybersecurity","Bachelor of Science in Computer Science",
                  "Master of Business Administration"],
    },
    "ut arlington": {
        "featured_name": "Bachelor of Science in Nursing",
        "reputation_note": "UTA's nursing program is the largest in Texas and one of the largest in the US, with exceptional NCLEX pass rates.",
        "program_url": "https://www.uta.edu/nursing",
        "top20": ["Bachelor of Science in Nursing","Bachelor of Science in Computer Science",
                  "Master of Business Administration"],
    },
    "ut el paso": {
        "featured_name": "Bachelor of Science in Engineering",
        "reputation_note": "UTEP Engineering is a nationally recognized Hispanic-serving institution for STEM, with top NSF funding and research programs.",
        "program_url": "https://engineering.utep.edu",
        "top20": ["Bachelor of Science in Engineering","Bachelor of Science in Computer Science"],
    },

    # ── NATIONAL ELITE ─────────────────────────────────────────────────────
    "massachusetts institute": {
        "featured_name": "Bachelor of Science in Electrical Engineering and Computer Science",
        "reputation_note": "MIT EECS is ranked #1 globally and has produced more Nobel laureates and tech founders than any other engineering program in the world.",
        "program_url": "https://www.eecs.mit.edu/academics-admissions/undergraduate-programs",
        "top20": ["Bachelor of Science in Electrical Engineering and Computer Science",
                  "Bachelor of Science in Computer Science","Master of Science in Computer Science",
                  "Doctor of Philosophy in Physics","Bachelor of Science in Aerospace Engineering"],
    },
    "stanford": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "Stanford CS is ranked #1 in the US and has spawned Google, Yahoo, Netflix, Sun Microsystems, and thousands of Silicon Valley companies.",
        "program_url": "https://cs.stanford.edu/academics/undergraduate",
        "top20": ["Bachelor of Science in Computer Science","Master of Business Administration",
                  "Master of Science in Computer Science","Juris Doctor",
                  "Bachelor of Science in Electrical Engineering"],
    },
    "harvard": {
        "featured_name": "Juris Doctor",
        "reputation_note": "Harvard Law is the oldest law school in the US, ranked #1 globally, and has produced 8 US Presidents and more Supreme Court justices than any other school.",
        "program_url": "https://hls.harvard.edu/jd-program",
        "top20": ["Juris Doctor","Master of Business Administration",
                  "Doctor of Philosophy in Economics","Doctor of Medicine",
                  "Bachelor of Arts in Computer Science","Master of Public Policy"],
    },
    "princeton": {
        "featured_name": "Bachelor of Arts in Economics",
        "reputation_note": "Princeton Economics is ranked top-3 globally and has produced 22 Nobel laureates including Paul Krugman, known for exceptional undergraduate research.",
        "program_url": "https://economics.princeton.edu/undergraduate",
        "top20": ["Bachelor of Arts in Economics","Bachelor of Science in Computer Science",
                  "Doctor of Philosophy in Mathematics","Master in Public Policy"],
    },
    "yale": {
        "featured_name": "Juris Doctor",
        "reputation_note": "Yale Law is ranked #1 in the US for the past 30 years, producing more federal judges, Supreme Court clerks, and Cabinet members than any other law school.",
        "program_url": "https://law.yale.edu/study-law-yale/jd-program",
        "top20": ["Juris Doctor","Bachelor of Arts in Economics",
                  "Doctor of Medicine","Master of Business Administration",
                  "Bachelor of Arts in Political Science"],
    },
    "columbia": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "Columbia Business School MBA is ranked top-10 globally and is the heart of Wall Street talent, with exceptional finance and investment banking placement.",
        "program_url": "https://business.columbia.edu/mba",
        "top20": ["Master of Business Administration","Juris Doctor","Doctor of Medicine",
                  "Bachelor of Arts in Computer Science","Bachelor of Arts in Economics"],
    },
    "university of pennsylvania": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "Wharton MBA is ranked #1 in the world for business and finance, producing more Fortune 500 CEOs than any other school.",
        "program_url": "https://mba.wharton.upenn.edu",
        "top20": ["Master of Business Administration","Juris Doctor","Doctor of Medicine",
                  "Bachelor of Science in Economics","Bachelor of Science in Computer Science"],
    },
    "carnegie mellon": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "CMU CS is ranked #1 in AI and robotics globally, producing more tech executives and AI researchers than virtually any other program.",
        "program_url": "https://www.cs.cmu.edu/academics/undergraduate",
        "top20": ["Bachelor of Science in Computer Science","Master of Science in Computer Science",
                  "Bachelor of Arts in Drama","Bachelor of Science in Electrical Engineering",
                  "Master of Science in Robotics"],
    },
    "johns hopkins": {
        "featured_name": "Doctor of Medicine",
        "reputation_note": "Johns Hopkins Medicine was ranked #1 in the US for 22 consecutive years and is the world's leader in biomedical research and clinical care.",
        "program_url": "https://www.hopkinsmedicine.org/som",
        "top20": ["Doctor of Medicine","Master of Public Health",
                  "Bachelor of Science in Biomedical Engineering","Master of Science in Applied Mathematics",
                  "Doctor of Philosophy in Neuroscience"],
    },
    "california institute": {
        "featured_name": "Bachelor of Science in Physics",
        "reputation_note": "Caltech Physics has produced 33 Nobel laureates and is ranked #1 globally for physics per capita — home to Einstein, Feynman, and Oppenheimer.",
        "program_url": "https://www.pma.caltech.edu/research-and-academics/physics",
        "top20": ["Bachelor of Science in Physics","Bachelor of Science in Computer Science",
                  "Bachelor of Science in Electrical Engineering","Doctor of Philosophy in Astrophysics"],
    },
    "duke": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "Duke's Fuqua School MBA is ranked top-15 globally with exceptional healthcare management and consulting placement.",
        "program_url": "https://www.fuqua.duke.edu/programs/daytime-mba",
        "top20": ["Master of Business Administration","Juris Doctor","Doctor of Medicine",
                  "Bachelor of Science in Computer Science","Bachelor of Science in Biomedical Engineering"],
    },
    "dartmouth": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "Tuck MBA at Dartmouth is consistently ranked top-10 globally for general management and produces exceptional finance and consulting talent.",
        "program_url": "https://www.tuck.dartmouth.edu/mba",
        "top20": ["Master of Business Administration","Bachelor of Arts in Economics",
                  "Bachelor of Arts in Computer Science"],
    },
    "cornell": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "Cornell CS is ranked top-5 nationally and is a co-founder of the NYC tech ecosystem through Cornell Tech, with exceptional AI research output.",
        "program_url": "https://www.cs.cornell.edu/undergrad",
        "top20": ["Bachelor of Science in Computer Science","Master of Business Administration",
                  "Bachelor of Science in Engineering","Juris Doctor","Doctor of Veterinary Medicine"],
    },
    "northwestern": {
        "featured_name": "Bachelor of Arts in Journalism",
        "reputation_note": "Northwestern's Medill School of Journalism is ranked #1 in the US and has produced more prominent journalists, editors, and media executives than any other school.",
        "program_url": "https://www.medill.northwestern.edu/journalism",
        "top20": ["Bachelor of Arts in Journalism","Master of Business Administration",
                  "Juris Doctor","Bachelor of Music","Bachelor of Science in Computer Science"],
    },
    "vanderbilt": {
        "featured_name": "Doctor of Medicine",
        "reputation_note": "Vanderbilt School of Medicine is ranked top-15 nationally for research and is home to pioneering advances in cancer research and genomics.",
        "program_url": "https://medschool.vanderbilt.edu",
        "top20": ["Doctor of Medicine","Master of Business Administration","Juris Doctor",
                  "Bachelor of Arts in Economics","Bachelor of Science in Computer Science"],
    },
    "notre dame": {
        "featured_name": "Juris Doctor",
        "reputation_note": "Notre Dame Law is ranked top-20 nationally with exceptional placement in Supreme Court clerkships and federal judiciary.",
        "program_url": "https://law.nd.edu",
        "top20": ["Juris Doctor","Master of Business Administration",
                  "Bachelor of Science in Computer Science","Bachelor of Arts in Economics"],
    },
    "georgetown": {
        "featured_name": "Juris Doctor",
        "reputation_note": "Georgetown Law is ranked top-14 nationally and is the largest law school in the US, with unmatched connections to Washington DC policy and government.",
        "program_url": "https://www.law.georgetown.edu",
        "top20": ["Juris Doctor","Master of Science in Foreign Service",
                  "Master of Business Administration","Bachelor of Arts in Political Science"],
    },
    "emory": {
        "featured_name": "Doctor of Medicine",
        "reputation_note": "Emory School of Medicine is ranked top-20 nationally and is home to the CDC's institutional partner, with exceptional global health research.",
        "program_url": "https://med.emory.edu",
        "top20": ["Doctor of Medicine","Master of Business Administration","Juris Doctor",
                  "Master of Public Health","Bachelor of Science in Computer Science"],
    },
    "tufts": {
        "featured_name": "Doctor of Veterinary Medicine",
        "reputation_note": "Tufts Cummings School of Veterinary Medicine is ranked top-5 in the US and is the premier veterinary school in New England.",
        "program_url": "https://vet.tufts.edu",
        "top20": ["Doctor of Veterinary Medicine","Bachelor of Arts in International Relations",
                  "Doctor of Medicine","Master of Arts in Law and Diplomacy"],
    },
    "boston university": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "BU CS has grown into a top-50 national program, with significant research in AI, systems security, and data science.",
        "program_url": "https://www.bu.edu/cs/undergraduate",
        "top20": ["Bachelor of Science in Computer Science","Master of Business Administration",
                  "Bachelor of Science in Journalism","Doctor of Medicine"],
    },
    "boston college": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "BC's Carroll School MBA is AACSB-accredited and ranked top-40 nationally with exceptional ethics and finance curriculum.",
        "program_url": "https://www.bc.edu/content/bc-web/schools/carroll-school/graduate/mba.html",
        "top20": ["Master of Business Administration","Juris Doctor",
                  "Bachelor of Science in Finance","Bachelor of Arts in Political Science"],
    },

    # ── BIG TEN / MIDWEST ─────────────────────────────────────────────────
    "university of michigan": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "Michigan Ross MBA is ranked top-12 globally with exceptional placement in consulting, finance, and general management.",
        "program_url": "https://michiganross.umich.edu/programs/full-time-mba",
        "top20": ["Master of Business Administration","Juris Doctor","Doctor of Medicine",
                  "Bachelor of Science in Computer Science","Bachelor of Science in Engineering"],
    },
    "ohio state": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "Ohio State Fisher MBA is ranked top-30 nationally with exceptional supply chain management and operations research programs.",
        "program_url": "https://fisher.osu.edu/graduate/fulltime-mba",
        "top20": ["Master of Business Administration","Bachelor of Science in Computer Science",
                  "Doctor of Medicine","Bachelor of Science in Nursing"],
    },
    "indiana university": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "IU Kelley MBA is ranked top-20 nationally and is consistently the top-ranked online MBA, with exceptional accounting and marketing programs.",
        "program_url": "https://kelley.iu.edu/programs/mba",
        "top20": ["Master of Business Administration","Bachelor of Science in Computer Science",
                  "Bachelor of Science in Accounting","Juris Doctor"],
    },
    "purdue": {
        "featured_name": "Bachelor of Science in Aeronautical and Astronautical Engineering",
        "reputation_note": "Purdue Aerospace is the #1 producer of astronauts in history, with 24 alumni having flown in space including Neil Armstrong.",
        "program_url": "https://engineering.purdue.edu/AAE",
        "top20": ["Bachelor of Science in Aeronautical and Astronautical Engineering",
                  "Bachelor of Science in Computer Science","Bachelor of Science in Engineering",
                  "Master of Business Administration"],
    },
    "university of illinois": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "UIUC CS is ranked #5 nationally and is the birthplace of the Mosaic browser, NCSA, and is one of the premier CS research universities globally.",
        "program_url": "https://cs.illinois.edu/academics/undergraduate",
        "top20": ["Bachelor of Science in Computer Science","Master of Science in Computer Science",
                  "Bachelor of Science in Electrical Engineering","Master of Business Administration"],
    },
    "northwestern university": {
        "featured_name": "Bachelor of Arts in Journalism",
        "reputation_note": "Northwestern Medill is ranked #1 for journalism in the US.",
        "program_url": "https://www.medill.northwestern.edu",
        "top20": ["Bachelor of Arts in Journalism","Master of Business Administration","Juris Doctor"],
    },
    "university of wisconsin": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "UW-Madison CS is ranked top-15 nationally with strong ties to the thriving Madison tech startup scene and exceptional research faculty.",
        "program_url": "https://www.cs.wisc.edu/undergraduate",
        "top20": ["Bachelor of Science in Computer Science","Master of Business Administration",
                  "Doctor of Philosophy in Chemistry","Bachelor of Science in Engineering"],
    },
    "university of minnesota": {
        "featured_name": "Doctor of Medicine",
        "reputation_note": "UMN Medical School is home to pioneering research in heart surgery, open heart surgery was invented here, and is consistently top-20 for NIH funding.",
        "program_url": "https://med.umn.edu",
        "top20": ["Doctor of Medicine","Master of Business Administration",
                  "Bachelor of Science in Computer Science","Master of Public Health"],
    },
    "michigan state": {
        "featured_name": "Bachelor of Science in Supply Chain Management",
        "reputation_note": "MSU's Eli Broad Supply Chain Management is ranked #1 in the nation for undergraduate supply chain, producing leaders at every Fortune 500 company.",
        "program_url": "https://broad.msu.edu/supply-chain",
        "top20": ["Bachelor of Science in Supply Chain Management","Master of Business Administration",
                  "Bachelor of Science in Computer Science","Doctor of Medicine"],
    },
    "penn state": {
        "featured_name": "Bachelor of Science in Engineering",
        "reputation_note": "Penn State Engineering is one of the largest engineering schools in the US and is consistently ranked top-20 for undergraduate engineering education.",
        "program_url": "https://www.engr.psu.edu/undergraduate",
        "top20": ["Bachelor of Science in Engineering","Master of Business Administration",
                  "Bachelor of Science in Computer Science","Bachelor of Science in Nursing"],
    },

    # ── WEST COAST ─────────────────────────────────────────────────────────
    "university of california, berkeley": {
        "featured_name": "Bachelor of Science in Electrical Engineering and Computer Science",
        "reputation_note": "UC Berkeley EECS is ranked #1 globally alongside MIT and Stanford, and is the birthplace of Unix, BSD, and foundational internet protocols.",
        "program_url": "https://eecs.berkeley.edu/academics/undergraduate",
        "top20": ["Bachelor of Science in Electrical Engineering and Computer Science",
                  "Master of Business Administration","Juris Doctor",
                  "Bachelor of Science in Computer Science","Doctor of Philosophy in Economics"],
    },
    "university of california, los angeles": {
        "featured_name": "Bachelor of Arts in Film and Television",
        "reputation_note": "UCLA School of Theater, Film and Television is ranked #1 in the US for film production and screenwriting, producing major Hollywood directors and writers.",
        "program_url": "https://www.tft.ucla.edu/programs",
        "top20": ["Bachelor of Arts in Film and Television","Doctor of Medicine",
                  "Master of Business Administration","Bachelor of Science in Computer Science",
                  "Juris Doctor"],
    },
    "university of southern california": {
        "featured_name": "Bachelor of Fine Arts in Film Production",
        "reputation_note": "USC School of Cinematic Arts is ranked #1 in the US and has produced more working Hollywood directors and producers than any school in the world.",
        "program_url": "https://cinema.usc.edu/programs/undergraduate",
        "top20": ["Bachelor of Fine Arts in Film Production","Master of Business Administration",
                  "Juris Doctor","Bachelor of Science in Computer Science",
                  "Doctor of Pharmacy"],
    },
    "university of washington": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "UW CS is ranked top-10 nationally and has direct pipelines to Amazon, Microsoft, and Boeing in one of the world's hottest tech markets.",
        "program_url": "https://www.cs.washington.edu/academics/ugrad",
        "top20": ["Bachelor of Science in Computer Science","Master of Science in Computer Science",
                  "Doctor of Medicine","Master of Business Administration",
                  "Bachelor of Science in Bioengineering"],
    },
    "university of california, san diego": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "UCSD CS is ranked top-15 nationally and is home to world-class research in HCI, systems, and bioinformatics.",
        "program_url": "https://cse.ucsd.edu/undergraduate",
        "top20": ["Bachelor of Science in Computer Science","Doctor of Medicine",
                  "Bachelor of Science in Bioengineering","Master of Science in Computer Science"],
    },
    "university of california, davis": {
        "featured_name": "Doctor of Veterinary Medicine",
        "reputation_note": "UC Davis School of Veterinary Medicine is ranked #1 in the world and is the largest vet school in the US, with unmatched agriculture and large animal programs.",
        "program_url": "https://www.vetmed.ucdavis.edu",
        "top20": ["Doctor of Veterinary Medicine","Bachelor of Science in Agricultural Science",
                  "Bachelor of Science in Computer Science","Master of Business Administration"],
    },
    "oregon state": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "OSU CS is one of the largest CS programs in the Pacific Northwest with a top-ranked online postbacc program and strong ties to the Portland tech scene.",
        "program_url": "https://eecs.oregonstate.edu/academics/undergrad",
        "top20": ["Bachelor of Science in Computer Science","Bachelor of Science in Engineering",
                  "Bachelor of Science in Forestry","Master of Business Administration"],
    },
    "university of oregon": {
        "featured_name": "Bachelor of Arts in Journalism",
        "reputation_note": "UO School of Journalism and Communication is one of the oldest journalism schools in the US and produces top talent in media and strategic communication.",
        "program_url": "https://journalism.uoregon.edu/undergraduate",
        "top20": ["Bachelor of Arts in Journalism","Bachelor of Science in Computer Science",
                  "Master of Business Administration"],
    },
    "arizona state": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "ASU CS is ranked top-20 nationally for online programs and is the fastest-growing CS school in the US with exceptional industry partnerships.",
        "program_url": "https://eecs.asu.edu/programs/undergraduate",
        "top20": ["Bachelor of Science in Computer Science","Master of Business Administration",
                  "Bachelor of Science in Journalism","Doctor of Medicine"],
    },
    "university of arizona": {
        "featured_name": "Doctor of Pharmacy",
        "reputation_note": "UA College of Pharmacy is ranked top-20 nationally with exceptional clinical programs and pharmaceutical sciences research.",
        "program_url": "https://pharmacy.arizona.edu/education/pharmd",
        "top20": ["Doctor of Pharmacy","Bachelor of Science in Computer Science",
                  "Master of Business Administration","Doctor of Medicine"],
    },
    "university of colorado": {
        "featured_name": "Bachelor of Science in Aerospace Engineering",
        "reputation_note": "CU Boulder Aerospace Engineering is ranked top-10 nationally and is the only school directly adjacent to NOAA, NIST, and NCAR research centers.",
        "program_url": "https://www.colorado.edu/aerospace",
        "top20": ["Bachelor of Science in Aerospace Engineering","Bachelor of Science in Computer Science",
                  "Master of Business Administration","Bachelor of Science in Environmental Engineering"],
    },
    "colorado state": {
        "featured_name": "Doctor of Veterinary Medicine",
        "reputation_note": "CSU College of Veterinary Medicine is ranked top-5 in the US, known for cutting-edge cancer research and large animal medicine.",
        "program_url": "https://www.cvmbs.colostate.edu/vetmed",
        "top20": ["Doctor of Veterinary Medicine","Bachelor of Science in Engineering",
                  "Master of Business Administration"],
    },

    # ── SOUTHEAST ──────────────────────────────────────────────────────────
    "university of florida": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "UF CS is ranked top-10 nationally for public universities and is home to CISE, one of the most research-active CS departments in the Southeast.",
        "program_url": "https://www.cise.ufl.edu/academics/undergraduate",
        "top20": ["Bachelor of Science in Computer Science","Master of Business Administration",
                  "Doctor of Medicine","Doctor of Pharmacy","Juris Doctor"],
    },
    "florida state": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "FSU College of Business is AACSB-accredited with highly ranked risk management and insurance programs.",
        "program_url": "https://business.fsu.edu/graduate/mba",
        "top20": ["Master of Business Administration","Bachelor of Science in Computer Science",
                  "Bachelor of Arts in Film","Doctor of Medicine"],
    },
    "university of miami": {
        "featured_name": "Doctor of Medicine",
        "reputation_note": "University of Miami Miller School of Medicine is ranked top-25 nationally and is a global leader in HIV/AIDS and neuroscience research.",
        "program_url": "https://med.miami.edu/education/md-program",
        "top20": ["Doctor of Medicine","Master of Business Administration","Juris Doctor",
                  "Bachelor of Arts in Music","Bachelor of Science in Marine Science"],
    },
    "university of georgia": {
        "featured_name": "Bachelor of Science in Agricultural and Applied Economics",
        "reputation_note": "UGA Terry College of Business and its Agricultural Economics program are consistently ranked among the best in the Southeast.",
        "program_url": "https://www.caes.uga.edu/departments/agricultural-applied-economics.html",
        "top20": ["Bachelor of Science in Agricultural and Applied Economics",
                  "Master of Business Administration","Juris Doctor",
                  "Bachelor of Science in Computer Science","Doctor of Pharmacy"],
    },
    "georgia tech": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "Georgia Tech CS is ranked #5 nationally, producing more software engineers per year than any other school, with exceptional co-op and startup programs.",
        "program_url": "https://www.cc.gatech.edu/academics/degree-programs/bachelors/computer-science",
        "top20": ["Bachelor of Science in Computer Science","Master of Science in Computer Science",
                  "Bachelor of Science in Aerospace Engineering","Bachelor of Science in Industrial Engineering",
                  "Master of Business Administration"],
    },
    "university of north carolina": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "UNC Kenan-Flagler MBA is ranked top-20 nationally with exceptional entrepreneurship and sustainability programs.",
        "program_url": "https://www.kenan-flagler.unc.edu/mba",
        "top20": ["Master of Business Administration","Doctor of Medicine","Juris Doctor",
                  "Bachelor of Arts in Journalism","Bachelor of Science in Computer Science"],
    },
    "north carolina state": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "NC State CS is ranked top-20 nationally for computer science and is at the heart of Research Triangle Park, one of the world's largest tech hubs.",
        "program_url": "https://www.csc.ncsu.edu/academics/undergrad",
        "top20": ["Bachelor of Science in Computer Science","Bachelor of Science in Engineering",
                  "Master of Business Administration","Bachelor of Science in Textile Technology"],
    },
    "wake forest": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "Wake Forest MBA is ranked top-50 nationally for ethics and social responsibility in business education.",
        "program_url": "https://business.wfu.edu/graduate/mba",
        "top20": ["Master of Business Administration","Juris Doctor",
                  "Bachelor of Arts in Economics"],
    },
    "clemson": {
        "featured_name": "Bachelor of Science in Engineering",
        "reputation_note": "Clemson Engineering is ranked top-20 nationally for undergraduate teaching and has exceptional automotive engineering research programs.",
        "program_url": "https://www.clemson.edu/cecas/departments",
        "top20": ["Bachelor of Science in Engineering","Bachelor of Science in Computer Science",
                  "Master of Business Administration"],
    },
    "university of south carolina": {
        "featured_name": "Master of International Business",
        "reputation_note": "USC Moore School's International Business program is ranked #1 in the US for undergraduate international business by US News.",
        "program_url": "https://sc.edu/study/colleges_schools/moore/international_business",
        "top20": ["Master of International Business","Master of Business Administration",
                  "Bachelor of Science in Computer Science"],
    },
    "university of alabama": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "UA Culverhouse MBA is ranked top-50 nationally and produces exceptional accounting and finance talent throughout the Southeast.",
        "program_url": "https://culverhouse.ua.edu/graduate-mba",
        "top20": ["Master of Business Administration","Bachelor of Science in Computer Science",
                  "Juris Doctor"],
    },
    "auburn": {
        "featured_name": "Bachelor of Science in Engineering",
        "reputation_note": "Auburn Engineering is consistently ranked top-25 for aerospace and mechanical engineering in the US, with strong ties to NASA and US defense.",
        "program_url": "https://eng.auburn.edu/academics/undergraduate",
        "top20": ["Bachelor of Science in Engineering","Doctor of Veterinary Medicine",
                  "Master of Business Administration","Bachelor of Science in Computer Science"],
    },
    "lsu": {
        "featured_name": "Bachelor of Science in Petroleum Engineering",
        "reputation_note": "LSU Petroleum Engineering is ranked top-5 in the US and produces the majority of petroleum engineers working in the Gulf of Mexico.",
        "program_url": "https://www.lsu.edu/eng/pete",
        "top20": ["Bachelor of Science in Petroleum Engineering","Master of Business Administration",
                  "Bachelor of Science in Computer Science","Juris Doctor"],
    },
    "tulane": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "Tulane Freeman MBA is ranked top-40 nationally with exceptional energy and social innovation programs.",
        "program_url": "https://freeman.tulane.edu/mba",
        "top20": ["Master of Business Administration","Doctor of Medicine",
                  "Juris Doctor","Master of Public Health"],
    },
    "university of tennessee": {
        "featured_name": "Bachelor of Science in Supply Chain Management",
        "reputation_note": "UT Haslam's Supply Chain Management program is ranked #3 in the nation, producing leaders at UPS, FedEx, and major logistics companies.",
        "program_url": "https://haslam.utk.edu/supply-chain-management",
        "top20": ["Bachelor of Science in Supply Chain Management","Master of Business Administration",
                  "Bachelor of Science in Computer Science","Juris Doctor"],
    },
    "university of kentucky": {
        "featured_name": "Doctor of Pharmacy",
        "reputation_note": "UK College of Pharmacy is ranked top-15 nationally and is known for cutting-edge pharmaceutical research in the Appalachian region.",
        "program_url": "https://pharmacy.uky.edu",
        "top20": ["Doctor of Pharmacy","Doctor of Medicine","Master of Business Administration",
                  "Bachelor of Science in Computer Science"],
    },
    "university of louisville": {
        "featured_name": "Doctor of Medicine",
        "reputation_note": "U of L School of Medicine is known for pioneering the first successful hand transplant in North America and exceptional research in cardiovascular medicine.",
        "program_url": "https://louisville.edu/medicine",
        "top20": ["Doctor of Medicine","Master of Business Administration",
                  "Bachelor of Science in Computer Science"],
    },
    "virginia tech": {
        "featured_name": "Bachelor of Science in Engineering",
        "reputation_note": "Virginia Tech Engineering is ranked top-20 nationally and is a global leader in architecture, aerospace, and civil engineering research.",
        "program_url": "https://eng.vt.edu/academics/undergraduate",
        "top20": ["Bachelor of Science in Engineering","Bachelor of Science in Computer Science",
                  "Master of Business Administration","Bachelor of Architecture"],
    },
    "university of virginia": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "UVA Darden MBA is ranked top-10 globally for case-based learning and produces exceptional management and strategy talent.",
        "program_url": "https://www.darden.virginia.edu/mba",
        "top20": ["Master of Business Administration","Juris Doctor","Doctor of Medicine",
                  "Bachelor of Science in Computer Science","Bachelor of Arts in Economics"],
    },
    "william & mary": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "W&M Mason MBA is ranked top-50 nationally and is one of the most selective MBA programs in the Mid-Atlantic region.",
        "program_url": "https://mason.wm.edu/programs/fulltime-mba",
        "top20": ["Master of Business Administration","Juris Doctor",
                  "Bachelor of Arts in Economics"],
    },

    # ── NORTHEAST ─────────────────────────────────────────────────────────
    "new york university": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "NYU Stern MBA is ranked top-20 globally with unmatched access to Wall Street and New York's financial, media, and tech industries.",
        "program_url": "https://www.stern.nyu.edu/programs-admissions/full-time-mba",
        "top20": ["Master of Business Administration","Juris Doctor","Bachelor of Fine Arts",
                  "Doctor of Medicine","Bachelor of Science in Computer Science"],
    },
    "fordham": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "Fordham Gabelli MBA offers exceptional access to Wall Street firms and New York City's financial sector from its Midtown Manhattan campus.",
        "program_url": "https://www.fordham.edu/gabelli-school-of-business/graduate-programs/mba",
        "top20": ["Master of Business Administration","Juris Doctor",
                  "Bachelor of Arts in Communication and Media Studies"],
    },
    "rensselaer": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "RPI CS is one of the oldest technology schools in the US and is ranked top-30 nationally for computer science research.",
        "program_url": "https://science.rpi.edu/computer-science/programs/bscs",
        "top20": ["Bachelor of Science in Computer Science","Bachelor of Science in Engineering",
                  "Master of Business Administration"],
    },
    "rochester": {
        "featured_name": "Doctor of Medicine",
        "reputation_note": "University of Rochester Medical Center is ranked top-25 for NIH funding and is a pioneer in biopsychosocial medicine.",
        "program_url": "https://www.urmc.rochester.edu/education/md-program.aspx",
        "top20": ["Doctor of Medicine","Bachelor of Music","Bachelor of Science in Computer Science",
                  "Master of Business Administration"],
    },
    "drexel": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "Drexel CS runs the longest co-op program in the US, with students completing 18 months of industry experience before graduation.",
        "program_url": "https://drexel.edu/cci/academics/undergraduate-programs/bs-in-cs",
        "top20": ["Bachelor of Science in Computer Science","Master of Business Administration",
                  "Doctor of Medicine","Bachelor of Science in Nursing"],
    },
    "lehigh": {
        "featured_name": "Bachelor of Science in Engineering",
        "reputation_note": "Lehigh Engineering is ranked top-50 nationally and is the birthplace of the Bethlehem Steel Corporation, with exceptional manufacturing and materials engineering.",
        "program_url": "https://engineering.lehigh.edu/undergraduate",
        "top20": ["Bachelor of Science in Engineering","Master of Business Administration",
                  "Bachelor of Science in Computer Science"],
    },
    "villanova": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "Villanova School of Business MBA is AACSB-accredited and ranked top-50 nationally for part-time and full-time programs.",
        "program_url": "https://www1.villanova.edu/university/business/graduate/mba.html",
        "top20": ["Master of Business Administration","Bachelor of Science in Computer Science",
                  "Bachelor of Science in Nursing"],
    },
    "temple": {
        "featured_name": "Bachelor of Business Administration",
        "reputation_note": "Temple Fox School of Business is ranked top-15 in the US for risk management and insurance.",
        "program_url": "https://fox.temple.edu/undergraduate/programs",
        "top20": ["Bachelor of Business Administration","Master of Business Administration",
                  "Juris Doctor","Bachelor of Science in Computer Science"],
    },
    "rutgers": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "Rutgers Business School MBA is ranked top-30 nationally for supply chain management and pharmaceutical management.",
        "program_url": "https://www.business.rutgers.edu/mba",
        "top20": ["Master of Business Administration","Juris Doctor","Doctor of Pharmacy",
                  "Bachelor of Science in Computer Science"],
    },
    "stony brook": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "Stony Brook CS is ranked top-50 nationally and has exceptional ties to the Long Island biotech and defense industries.",
        "program_url": "https://www.cs.stonybrook.edu/students/Undergraduate-Studies",
        "top20": ["Bachelor of Science in Computer Science","Doctor of Medicine",
                  "Master of Science in Computer Science"],
    },
    "syracuse": {
        "featured_name": "Bachelor of Arts in Public Communications",
        "reputation_note": "Syracuse Newhouse School is ranked #2 in the US for communications and journalism, producing more media executives than almost any other school.",
        "program_url": "https://newhouse.syr.edu/programs/undergraduate",
        "top20": ["Bachelor of Arts in Public Communications","Master of Business Administration",
                  "Bachelor of Science in Computer Science","Juris Doctor"],
    },
    "university of connecticut": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "UConn School of Business MBA is AACSB-accredited and highly ranked for healthcare management in Connecticut's insurance capital.",
        "program_url": "https://business.uconn.edu/program/full-time-mba",
        "top20": ["Master of Business Administration","Doctor of Pharmacy",
                  "Bachelor of Science in Computer Science"],
    },
    "university of maryland": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "UMD CS is ranked top-20 nationally and is directly adjacent to NSA, NASA Goddard, and the NIH — producing more federal tech talent than nearly any school.",
        "program_url": "https://www.cs.umd.edu/undergrad/programs/cs-program",
        "top20": ["Bachelor of Science in Computer Science","Master of Business Administration",
                  "Bachelor of Science in Aerospace Engineering","Juris Doctor"],
    },
    "george washington": {
        "featured_name": "Master of Science in Cybersecurity",
        "reputation_note": "GWU's School of Engineering is DC's top tech school, with unmatched access to federal agencies, think tanks, and national security organizations.",
        "program_url": "https://www.seas.gwu.edu/ms-cybersecurity",
        "top20": ["Master of Science in Cybersecurity","Master of Business Administration",
                  "Juris Doctor","Master of Science in International Affairs",
                  "Bachelor of Science in Computer Science"],
    },
    "american university": {
        "featured_name": "Master of Science in International Affairs",
        "reputation_note": "AU School of International Service is ranked #2 in the US for international affairs, with unparalleled access to Washington DC's policy and diplomatic community.",
        "program_url": "https://www.american.edu/sis/graduate/ma-sia.cfm",
        "top20": ["Master of Science in International Affairs","Master of Business Administration",
                  "Juris Doctor","Bachelor of Arts in Political Science"],
    },
    "howard university": {
        "featured_name": "Doctor of Medicine",
        "reputation_note": "Howard College of Medicine is one of the nation's premier HBCUs for medicine and has produced more Black physicians than any other medical school in US history.",
        "program_url": "https://medicine.howard.edu",
        "top20": ["Doctor of Medicine","Juris Doctor","Doctor of Pharmacy",
                  "Master of Business Administration","Bachelor of Science in Computer Science"],
    },
    "george mason": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_name": "GMU CS is ranked top-50 nationally and is the largest university in Virginia, with exceptional ties to the DC tech and federal government sectors.",
        "program_url": "https://cs.gmu.edu/current-students/bs-in-cs",
        "top20": ["Bachelor of Science in Computer Science","Master of Science in Cybersecurity",
                  "Master of Business Administration"],
    },

    # ── SOUTHWEST / MOUNTAIN ──────────────────────────────────────────────
    "brigham young": {
        "featured_name": "Master of Business Administration",
        "reputation_note": "BYU Marriott MBA is ranked top-20 nationally and offers one of the lowest-cost MBA programs at a top school, with exceptional accounting and finance placement.",
        "program_url": "https://marriottschool.byu.edu/mba",
        "top20": ["Master of Business Administration","Bachelor of Science in Computer Science",
                  "Bachelor of Science in Accounting","Juris Doctor"],
    },
    "university of utah": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "Utah CS is ranked top-10 nationally for computer graphics and visualization — the birthplace of modern computer graphics with alumni including John Warnock of Adobe.",
        "program_url": "https://www.cs.utah.edu/undergraduate",
        "top20": ["Bachelor of Science in Computer Science","Master of Business Administration",
                  "Doctor of Medicine","Bachelor of Fine Arts in Animation"],
    },
    "university of new mexico": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "UNM CS has exceptional research in quantum computing and is the top CS program in New Mexico with ties to Sandia and Los Alamos National Labs.",
        "program_url": "https://cs.unm.edu/undergraduate",
        "top20": ["Bachelor of Science in Computer Science","Doctor of Medicine",
                  "Master of Business Administration","Bachelor of Science in Engineering"],
    },
    "oklahoma state": {
        "featured_name": "Bachelor of Science in Accounting",
        "reputation_note": "OSU Spears School of Business Accounting program is consistently ranked top-10 nationally for CPA pass rates.",
        "program_url": "https://business.okstate.edu/accounting",
        "top20": ["Bachelor of Science in Accounting","Master of Business Administration",
                  "Bachelor of Science in Engineering"],
    },
    "university of oklahoma": {
        "featured_name": "Bachelor of Science in Petroleum Engineering",
        "reputation_note": "OU Petroleum Engineering is ranked top-5 nationally and has produced more petroleum engineers for the energy industry than nearly any other school.",
        "program_url": "https://engineering.ou.edu/petroleum",
        "top20": ["Bachelor of Science in Petroleum Engineering","Master of Business Administration",
                  "Juris Doctor","Bachelor of Science in Computer Science"],
    },
    "university of kansas": {
        "featured_name": "Doctor of Pharmacy",
        "reputation_note": "KU School of Pharmacy is ranked top-20 nationally and is known for exceptional pharmaceutical chemistry research.",
        "program_url": "https://pharmacy.ku.edu/pharm-d-degree",
        "top20": ["Doctor of Pharmacy","Doctor of Medicine","Master of Business Administration",
                  "Bachelor of Science in Computer Science"],
    },
    "kansas state": {
        "featured_name": "Bachelor of Science in Architecture",
        "reputation_note": "K-State Architecture is ranked top-15 nationally for architecture education and has one of the strongest student-to-faculty ratios in the country.",
        "program_url": "https://www.arch.ksu.edu",
        "top20": ["Bachelor of Science in Architecture","Bachelor of Science in Engineering",
                  "Doctor of Veterinary Medicine"],
    },
    "iowa state": {
        "featured_name": "Bachelor of Science in Engineering",
        "reputation_note": "Iowa State Engineering is ranked top-25 nationally for engineering and is the birthplace of the first digital computer, ATANASOFF-BERRY.",
        "program_url": "https://www.engineering.iastate.edu/academics/undergraduate",
        "top20": ["Bachelor of Science in Engineering","Bachelor of Science in Computer Science",
                  "Master of Business Administration","Doctor of Veterinary Medicine"],
    },
    "university of iowa": {
        "featured_name": "Master of Fine Arts in Creative Writing",
        "reputation_note": "Iowa's MFA in Creative Writing is the original and most prestigious in the world, having produced more published American authors than any program in history.",
        "program_url": "https://writersworkshop.uiowa.edu",
        "top20": ["Master of Fine Arts in Creative Writing","Doctor of Medicine",
                  "Master of Business Administration","Juris Doctor",
                  "Bachelor of Science in Computer Science"],
    },
    "university of missouri": {
        "featured_name": "Bachelor of Arts in Journalism",
        "reputation_note": "Mizzou's School of Journalism is the world's first journalism school (founded 1908) and is consistently ranked top-5 in the US for journalism education.",
        "program_url": "https://journalism.missouri.edu/undergraduate",
        "top20": ["Bachelor of Arts in Journalism","Doctor of Medicine",
                  "Master of Business Administration","Juris Doctor"],
    },
    "university of nebraska": {
        "featured_name": "Bachelor of Science in Computer Science",
        "reputation_note": "UNL CS is ranked top-50 nationally and is the flagship tech program in Nebraska, with exceptional ties to Gallup, InfoSonics, and agtech startups.",
        "program_url": "https://cse.unl.edu/undergraduate",
        "top20": ["Bachelor of Science in Computer Science","Bachelor of Science in Agricultural Engineering",
                  "Master of Business Administration"],
    },

}  # end KNOWN_FEATURED
